const REDO_PUBLIC_API_HOSTNAME = 'api.getredo.com';
const REDO_PUBLIC_API_HOSTNAME_LOCAL = 'localhost:8001';

const REDO_REQUIRED_HOSTNAMES = [
  REDO_PUBLIC_API_HOSTNAME,
  REDO_PUBLIC_API_HOSTNAME_LOCAL
];

export {
  REDO_REQUIRED_HOSTNAMES,
  REDO_PUBLIC_API_HOSTNAME,
  REDO_PUBLIC_API_HOSTNAME_LOCAL,
};